apiVersion: apps/v1
kind: Deployment
metadata:
  name: makeline-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: makeline-service
  template:
    metadata:
      labels:
        app: makeline-service
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: makeline-service-account
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: makeline-service
        image: ghcr.io/pauldotyu/aks-store-demo/makeline-service:latest
        ports:
        - containerPort: 3001
        envFrom:
        - configMapRef:
            name: makeline-service-configs
        resources:
          requests:
            cpu: 1m
            memory: 6Mi
          limits:
            cpu: 5m
            memory: 20Mi
        readinessProbe:
          httpGet:
            path: /health
            port: 3001
          failureThreshold: 3
          initialDelaySeconds: 3
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 3001
          failureThreshold: 5
          initialDelaySeconds: 3
          periodSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: makeline-service
spec:
  ports:
  - name: http
    port: 3001
    targetPort: 3001
  selector:
    app: makeline-service
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: makeline-service
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: makeline-service
  unhealthyPodEvictionPolicy: AlwaysAllow